package com.day4;

public class ExceptionHandling {
    public static void main(String[] args) {

       
        try {
            int[] numbers = new int[5];

            for (int i = 0; i<= 5; i++) {  
                numbers[i] = i+1;   
                System.out.println(numbers[i]);
            }

        } catch (Exception ex) {
            System.out.println(ex + ex.getMessage());  //java.lang.ArrayIndexOutOfBoundsException
        }

        System.out.println();

        
        
        try {
             String name = null;
        	
            System.out.println(name.charAt(0));
            
        } catch (Exception ex) {
            System.out.println(ex + " " + ex.getMessage()); //java.lang.NullPointerException
        }

        System.out.println();

    }
}
